# See http://docs.spring.io/spring-boot/docs/1.1.4.RELEASE/reference/htmlsingle/#boot-features-external-config-profile-specific-properties
# for more details about creating profile-specific property files

# See http://docs.spring.io/spring-boot/docs/1.1.4.RELEASE/reference/htmlsingle/#howto-initialize-a-database-using-jpa
# for more details and options on initializing a production database
#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=validate

#server.context-path=/exptracker
## Replace with your connection string
#spring.datasource.url=jdbc:mysql://exptrackerdb.citdcqi7wmsj.us-west-2.rds.amazonaws.com:3306/exptrackerdb
#
## Replace with your credentials
#spring.datasource.username=nitin
#spring.datasource.password=summer2016
#
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.datasource.tomcat.initial-size=5
#spring.datasource.tomcat.max-active=10
#spring.thymeleaf.cache=false

server:
  context-path: /exptracker

spring:
  datasource:
    url: jdbc:mysql://exptrackerdb.citdcqi7wmsj.us-west-2.rds.amazonaws.com:3306/exptrackerdb
    username: nitin
    password: summer2016
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 5
      max-active: 10
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      clientId: 966859561577-37ejd1in1aci783msv6vbqh6snph82kv.apps.googleusercontent.com
      clientSecret: QXVMKZrwnUx0Gu7BGJfv511k
      accessTokenUri: https://accounts.google.com/o/oauth2/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#      tokenName: oauth_token
      authenticationScheme: query
#      clientAuthenticationScheme: form
      pre-established-redirect-uri: http://localhost:8080/exptracker
      scope: profile email
    resource:
       userInfoUri: https://www.googleapis.com/plus/v1/people/me
      
      